# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc9278bed8d530a6a5b18632c4dc788164d053676c073b26080d95b190a6ff52de7d1bf30ea43e82462c63ce4201055f03db59b877684626c44abb0b0b477ddf

test:
  secret_key_base: ec5ad96e5d7cfca6c5c60d87ef79f7590bebcf545077043e55d0a8e1e8ff2bc0d21f2748933850bc63f7ba307d25edcd2f210233a2684aa7892f120299f66147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
